export const templates = [
  {
    id: "default",
    name: "Default",
    config: {
      text: "15 Programming Tips You NEED to Know! 💻🚀",
      threadText: "A thread 🧵",
      username: "@musa_codes",
      backgroundColor: "#000000",
      backgroundImage: "",
      textColor: "#ffffff",
      fontSize: 32,
      threadFontSize: 18,
      fontFamily: "Inter",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
      codeBlock: "",
      codeLanguage: "javascript",
      codePosition: "above",
      showCodeBlock: false,
      codeTheme: "dark",
    },
  },
  {
    id: "blue-gradient",
    name: "Blue Theme",
    config: {
      text: "🚀 15 Programming Tips You NEED to Know!",
      threadText: "A thread worth saving",
      username: "musa_codes",
      backgroundColor: "#1e3a8a",
      backgroundImage: "",
      textColor: "#ffffff",
      fontSize: 36,
      threadFontSize: 20,
      fontFamily: "Poppins",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
      codeBlock: "",
      codeLanguage: "javascript",
      codePosition: "above",
      showCodeBlock: false,
      codeTheme: "dark",
    },
  },
  {
    id: "gradient",
    name: "Gradient",
    config: {
      text: "10 Ways to Improve Your Code Quality ✨",
      threadText: "A thread 🧵",
      username: "@musa_codes",
      backgroundColor: "#667eea",
      backgroundImage: "",
      textColor: "#ffffff",
      fontSize: 32,
      threadFontSize: 18,
      fontFamily: "Montserrat",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
      codeBlock: "",
      codeLanguage: "javascript",
      codePosition: "above",
      showCodeBlock: false,
      codeTheme: "dark",
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    config: {
      text: "The Art of Clean Code",
      threadText: "",
      username: "@musa_codes",
      backgroundColor: "#ffffff",
      backgroundImage: "",
      textColor: "#000000",
      fontSize: 36,
      threadFontSize: 18,
      fontFamily: "Playfair Display",
      fontWeight: "normal",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: false,
      codeBlock: "",
      codeLanguage: "javascript",
      codePosition: "above",
      showCodeBlock: false,
      codeTheme: "light",
    },
  },
  {
    id: "tech",
    name: "Tech",
    config: {
      text: "The Future of AI Development",
      threadText: "My thoughts 💭",
      username: "@musa_codes",
      backgroundColor: "#0f172a",
      backgroundImage: "",
      textColor: "#38bdf8",
      fontSize: 32,
      threadFontSize: 18,
      fontFamily: "Source Code Pro",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
      codeBlock: "",
      codeLanguage: "javascript",
      codePosition: "above",
      showCodeBlock: false,
      codeTheme: "dark",
    },
  },
  {
    id: "vibrant",
    name: "Vibrant",
    config: {
      text: "5 Design Principles Every Developer Should Know",
      threadText: "Design thread 🎨",
      username: "@musa_codes",
      backgroundColor: "#6d28d9",
      backgroundImage: "",
      textColor: "#ffffff",
      fontSize: 30,
      threadFontSize: 18,
      fontFamily: "Nunito",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
      codeBlock: "",
      codeLanguage: "javascript",
      codePosition: "above",
      showCodeBlock: false,
      codeTheme: "dark",
    },
  },
  {
    id: "professional",
    name: "Professional",
    config: {
      text: "Building Scalable Systems: Best Practices",
      threadText: "Professional insights",
      username: "@musa_codes",
      backgroundColor: "#1e293b",
      backgroundImage: "",
      textColor: "#f8fafc",
      fontSize: 28,
      threadFontSize: 18,
      fontFamily: "Lato",
      fontWeight: "normal",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
      codeBlock: "",
      codeLanguage: "javascript",
      codePosition: "above",
      showCodeBlock: false,
      codeTheme: "dark",
    },
  },
  {
    id: "code-focused",
    name: "Code Focus",
    config: {
      text: "Clean Code Principles Every Developer Should Follow",
      threadText: "Code tips 💻",
      username: "@musa_codes",
      backgroundColor: "#0d1117",
      backgroundImage: "",
      textColor: "#f0f6fc",
      fontSize: 28,
      threadFontSize: 18,
      fontFamily: "Source Code Pro",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
      codeBlock: `function cleanCode() {
  // Write self-documenting code
  const isUserValid = checkUserPermissions();
  
  if (isUserValid) {
    return processUserRequest();
  }
  
  throw new Error('Invalid user');
}`,
      codeLanguage: "javascript",
      codePosition: "below",
      showCodeBlock: true,
      codeTheme: "dark",
    },
  },
]
