export const templates = [
  {
    id: "default",
    name: "Default",
    config: {
      text: "15 Programming Tips You NEED to Know! 💻🚀",
      threadText: "A thread 🧵",
      username: "@musa_codes",
      backgroundColor: "#000000",
      backgroundImage: "",
      textColor: "#ffffff",
      fontSize: 32,
      threadFontSize: 18,
      fontFamily: "Inter",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
    },
  },
  {
    id: "blue-gradient",
    name: "Blue Theme",
    config: {
      text: "🚀 15 Programming Tips You NEED to Know!",
      threadText: "A thread worth saving",
      username: "musa_codes",
      backgroundColor: "#1e3a8a",
      backgroundImage: "",
      textColor: "#ffffff",
      fontSize: 36,
      threadFontSize: 20,
      fontFamily: "Inter",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
    },
  },
  {
    id: "gradient",
    name: "Gradient",
    config: {
      text: "10 Ways to Improve Your Code Quality ✨",
      threadText: "A thread 🧵",
      username: "@musa_codes",
      backgroundColor: "#667eea",
      backgroundImage: "",
      textColor: "#ffffff",
      fontSize: 32,
      threadFontSize: 18,
      fontFamily: "Inter",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
    },
  },
  {
    id: "minimal",
    name: "Minimal",
    config: {
      text: "The Art of Clean Code",
      threadText: "",
      username: "@musa_codes",
      backgroundColor: "#ffffff",
      backgroundImage: "",
      textColor: "#000000",
      fontSize: 36,
      threadFontSize: 18,
      fontFamily: "Georgia",
      fontWeight: "normal",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: false,
    },
  },
  {
    id: "tech",
    name: "Tech",
    config: {
      text: "The Future of AI Development",
      threadText: "My thoughts 💭",
      username: "@musa_codes",
      backgroundColor: "#0f172a",
      backgroundImage: "",
      textColor: "#38bdf8",
      fontSize: 32,
      threadFontSize: 18,
      fontFamily: "monospace",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
    },
  },
  {
    id: "vibrant",
    name: "Vibrant",
    config: {
      text: "5 Design Principles Every Developer Should Know",
      threadText: "Design thread 🎨",
      username: "@musa_codes",
      backgroundColor: "#6d28d9",
      backgroundImage: "",
      textColor: "#ffffff",
      fontSize: 30,
      threadFontSize: 18,
      fontFamily: "Verdana",
      fontWeight: "bold",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
    },
  },
  {
    id: "professional",
    name: "Professional",
    config: {
      text: "Building Scalable Systems: Best Practices",
      threadText: "Professional insights",
      username: "@musa_codes",
      backgroundColor: "#1e293b",
      backgroundImage: "",
      textColor: "#f8fafc",
      fontSize: 28,
      threadFontSize: 18,
      fontFamily: "Arial",
      fontWeight: "normal",
      contentImage: "",
      contentImageSize: 200,
      imagePosition: "above",
      showContentImage: false,
      showThreadText: true,
    },
  },
]
